API/urls.py
from django.urls import path
from django.conf import settings

from API.views.photo.collection import PhotoCollectionView
from API.views.user.details import UserDetailsView
app_name = 'API'

urlpatterns = [
    path('v1/photo_collection/', PhotoCollectionView.as_view()),
    path('v1/user_details/', UserDetailsView.as_view()),
]

photo_backend_snp/urls.py
from django.contrib import admin
from django.urls import path, include

from .yasg import urlpatterns as yasg_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('web_site.urls')),
    path('api/', include('API.urls')),
]

urlpatterns += yasg_urls

web_site/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from web_site.views.user import registration, email_login, logout, change, change_key, personal_profile
from web_site.views.main_pages import main_page, personal_cabinet, main_page
from web_site.views.photo import upload, details, photo_change, photo_delete, photo_delete_cancel, likes
from web_site.views.comment import list_create_comment_view, update_delete_comment_view

app_name = 'web_site'

urlpatterns = [
    path('', main_page.HomeView.as_view(), name='home'),
    # User urls
    path('register/', registration.UserRegistrationView.as_view(), name='register'),
    path('login/', email_login.UserLoginView.as_view(), name='login'),
    path('logout/', logout.UserLogoutView.as_view(), name='logout'),
    path('profile/', personal_profile.UserPersonalProfileView.as_view(), name='profile'),
    path('api-token/', change_key.GenerateNewTokenView.as_view(), name='api_token'),
    path('cabinet/', personal_cabinet.CabinetView.as_view(), name='cabinet'),
    path('change/', change.UserChangeView.as_view(), name='change'),
    # Photo urls
    path('upload/', upload.PhotoUploadView.as_view(), name='photo_upload'),
    path('photo/<int:pk>/', details.PhotoDetailView.as_view(), name='photo_details'),
    path('photo_change/<int:pk>/', photo_change.PhotoChangeView.as_view(), name='photo_change'),
    path('photo_delete/<int:pk>', photo_delete.PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo_delete_cancel/<int:pk>', photo_delete_cancel.PhotoCancelDeleteView.as_view(), name='photo_delete_cancel'),
    path('photo_like/<int:pk>', likes.LikeView.as_view(), name='photo_like'),
    # Comments urls
    path('<str:parent>/<int:parent_id>/comments/', list_create_comment_view.ListCreateCommentView.as_view(), name='comments_list_create'),
    path('comments/<int:comment_id>', update_delete_comment_view.UpdateDeleteCommentView.as_view(), name='comments_update_delete')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models_module/models/comment/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

from models_module.managers.comment.manager import CommentManager
from models_module.models import User


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='comments', related_query_name='comments')
    text = models.CharField(max_length=500, verbose_name="Comment text")

    # Recreate error with "wrong" names
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, related_name="content_type_comments")
    object_id = models.PositiveIntegerField()
    owner = GenericForeignKey('content_type', 'object_id')

    comment_count = models.IntegerField(default=0, null=True)

    comments = GenericRelation('Comment')

    collection = CommentManager()

    class Meta:
        db_table = 'comments'
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

models_module/models/like/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from models_module.models.photo.models import Photo
from models_module.models.user.models import User


# Junction table
class Like(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE,
                              related_name='likes',
                              related_query_name='likes')

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='likes',
                             related_query_name='likes')

web_site/templates/_comment.html
{% load static %}
{% block content %}
    <div class="card comment" data-comment-id="{{ comment.id }}">
        <div class="card-body">
            <div class="card-title"><img class="rounded" src="{{ comment.user.avatar.url }}" width="50"
                                         height="50"> {{ comment.user.get_full_name }}
            </div>
            <div class="card-text">
                {{ comment.text }}
            </div>
        </div>
        {% if user.is_authenticated %}
            <div class="comment-control-buttons">
                {% if request.user.pk == comment.user_id %}
                    <button class="btn btn-warning" data-delete-btn-comment-id="{{ comment.id }}">
                        <i class="fa-solid fa-comment-slash"></i>
                    </button>
                    <button id="change-comment-btn" class="btn btn-warning change-comment-btn"
                            data-change-btn-comment-id="{{ comment.id }}"
                            data-method="PUT">
                        <i class="fa-solid fa-marker"></i>
                    </button>
                {% endif %}
                <button id="create-subcomment-btn" class="btn btn-warning create-subcomment-btn" data-thread-btn-comment-id="{{ comment.id }}"
                        data-method="POST">
                    <i class="fa-solid fa-comments"></i>
                </button>
            </div>
        {% endif %}
        {% if comment.comments.all %}
            <a class="get-answers-btn">Show answers ( {{ comment.comment_count }} )</a>
            <div class="sub-comments" data-comment-id="{{ comment.id }}">
                {% for comment in comment.comments.all %}
{#                    {% include '_comment.html' with comment=comment %}#}
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

web_site/templates/change_photo.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% block content %}
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% bootstrap_form change_form %}
        {% buttons %}
            <button type="submit" class="btn btn-warning">{% translate 'Submit' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

web_site/templates/change_user.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% block content %}
    <form action="{% url 'web_site:change' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% bootstrap_form change_form %}
        {% buttons %}
            <button type="submit" class="btn btn-warning">{% translate 'Submit' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

{% if avatar %}
<img src="{{ avatar.url }}" alt="img">
{% endif %}

web_site/templates/comments.html
{% load i18n %}
{% load static %}

{% block content %}
        {% for comment in comment_list %}
            {% include '_comment.html' with comment=comment %}
        {% endfor %}
{% endblock %}
{% block scripts %}
{% endblock %}

web_site/templates/likes.html
{% block content %}
    <div style="display: flex">
        {% if request.user.is_authenticated %}
            <span class="{% if not photo.is_liked %}d-none{% endif %} like-btn{{ photo.id }}" id="unlike"
                    value="{{ photo.id }}"
                    data-unlike-photo-id="{{ photo.id }}" style="background: transparent; border: none;"
                    url="{% url 'web_site:photo_like' photo.id %}"><i class="fa-solid fa-heart"></i></span>
            <span class="{% if photo.is_liked %}d-none{% endif %} unlike-btn{{ photo.id }}" id="like"
                    value="{{ photo.id }}"
                    data-like-photo-id="{{ photo.id }}" style="background: transparent; border: none;"
                    url="{% url 'web_site:photo_like' photo.id %}"><i class="fa-regular fa-heart"></i></span>

        {% endif %}
        <div class="like-counter{{ photo.id }}" style="margin-left: 4px">{{ photo.likes_count }}</div>
    </div>
{% endblock %}

web_site/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load i18n %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% translate 'Login with email' %}</button>
            <a class="btn btn-primary" href="{% url 'web_site:registration' %}">{% translate 'Create an account' %}</a>
        {% endbuttons %}
    </form>
{% endblock %}

web_site/templates/main_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="album py-5 asa" id="photos">
        {% include 'object_collection.html' %}
        {% include 'pagination.html' %}
    </div>
{% endblock %}
<!-- SCRIPTS -->
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/async_pagination.js' %}"></script>
{% endblock %}

web_site/templates/navbar.html
{% load static %}
{% load i18n %}

{% block navbar %}
    {% if user.is_authenticated %}
        <nav class="navbar navbar-light bg-warning">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'web_site:cabinet' %}">
                    <img src="{{ user.avatar.url }}" alt="" width="30" height="30"
                         class="d-inline-block align-text-top">
                    {{ request.user.get_full_name }}
                </a>
                <div class="dropdown notifications">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Notifications
                    </button>
                    <div class="dropdown-menu notifications-menu" aria-labelledby="dropdownMenu2">
                    </div>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li><a class="dropdown-item" href="{% url 'web_site:home' %}">{% translate 'Main page' %}</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'web_site:cabinet' %}">{% translate 'Personal cabinet' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'web_site:logout' %}">{% translate 'Logout' %}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% else %}
        {% include 'modal_login.html' %}
        <nav class="navbar navbar-light bg-warning">
            <div class="container-fluid">
            </div>
            <div class="navbar-brand d-inline-block">{% translate 'Welcome!' %}</div>
            <button type="button" class="btn btn-dark" data-bs-toggle="modal"
                    data-bs-target="#login">{% translate 'Login' %}</button>
        </nav>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    {% if user.is_authenticated %}
        <script type="text/javascript" src="{% static 'js/websocket_notifications.js' %}"></script>
    {% endif %}
{% endblock %}

web_site/templates/object_collection.html
{% load i18n %}
{% load static %}

{% block content %}
    <div class="photos-collection">
        <div>
            <form class="d-flex" id="search-bar" name="search">
                <input name="search_string" class="form-control mr-sm-2" type="search" placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-warning my-2 my-sm-0">Search</button>
            </form>
            <li class="nav-item dropdown">
                <button class="btn btn-warning dropdown-toggle" id="navbarDropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% translate "Sort by:" %}
                </button>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="publish_date">
                        {% translate "Publish date (Asc)" %}</a>
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="-publish_date">
                        {% translate "Publish date (Desc)" %}</a>
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="likes_count">
                        {% translate "Likes (Asc)" %}</a>
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="-likes_count">
                        {% translate "Likes (Desc)" %}</a>
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="comment_count">
                        {% translate "Comments (Asc)" %}</a>
                    <a class="dropdown-item" id="sort-btn"
                       data-sort-by="-comment_count">
                        {% translate "Comments (Desc)" %}</a>
                </div>
            </li>
        </div>
        <div class="container">
            {% if object_list %}
                <div class="row row-cols-1 row-cols-sm2 row-cols-md-4 g-2">
                    {% for photo in object_list %}
                        <div class="col">
                            <div class="card">
                                <a href="{% url 'web_site:photo_details' photo.id %}">
                                    <img class="card-img-top" src="{{ photo.image_size_big.url }}" alt="Card image cap">
                                </a>
                                <div class="card-body" style="background: #f7f7f7;">
                                    <div>
                                        Author: {{ photo.owner.get_full_name }}
                                        <div>
                                            Title: {{ photo.name }}
                                        </div>
                                    </div>
                                    {% include 'likes.html' %}
                                    <i class="fa-solid fa-comment-dots"></i> {{ photo.comment_count }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>Nothing was found</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/search_and_sort.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax_likes.js' %}"></script>
{% endblock %}

web_site/templates/pagination.html
{% load i18n %}
{% block content %}

    <div class="pagination" id="pagination">
            <span class="step-links">
                    <button class="first-page-btn btn btn-warning {% if not object_list.has_previous %}d-none{% endif %}"
                            value="1"
                            style="color: black;text-decoration: none;background: #ffc107;">&laquo; first</button>
                    <button class="previous-page-btn btn btn-warning {% if not object_list.has_previous %}d-none{% endif %}"
                            value="{{ previous_page_number }}"
                            style="color: black;text-decoration: none;background: #ffc107;">previous</button>
            </span>
        <span class="current">
            <span class="current-page" value="">{{ object_list.number }}</span> of {{ object_list.paginator.num_pages }}

                <button class="next-page-btn btn btn-warning {% if not object_list.has_next %}d-none{% endif %}"
                        value="{{ object_list.next_page_number }}"
                        style="color: black;text-decoration: none;background: #ffc107;">next</button>
                <button class="last-page-btn btn btn-warning {% if not object_list.has_next %}d-none{% endif %}"
                        value="{{ object_list.paginator.num_pages }}"
                        style="color: black;text-decoration: none;background: #ffc107;">last &raquo;</button>
            </span>
    </div>
{% endblock %}

web_site/templates/personal_cabinet.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 d-auto ml-sm-auto bg-light sidebar">
            <ul class="nav nav-pills flex-column mb-auto">
                {% include 'user_details.html' %}
            </ul>
        </div>
        <div class="album col-md-9 ml-sm-auto col-lg-10 pt-3 px-4" id="photos">
            {% include 'object_collection.html' %}
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
{% endblock %}
<!-- SCRIPTS -->
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/async_pagination.js' %}"></script>
{% endblock %}

web_site/templates/photo_details.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="photo card mb-3" id="photo" data-photo-id="{{ photo.id }}">
            <img class="card-img-top" alt="image" src="{{ photo.image.url }}">
            <div class="card-body">
                {% if request.user.id == photo.owner.id %}
                    <a class="btn btn-warning"
                       href="{% url 'web_site:photo_change' photo.id %}"><i class="fa-solid fa-file-pen"></i></a>
                    {% if photo.mark_as_deleted_at is None %}
                        <a class="btn btn-warning"
                           href="{% url 'web_site:photo_delete' photo.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    {% else %}
                        <a class="btn btn-warning"
                           href="{% url 'web_site:photo_delete_cancel' photo.id %}"><i
                                class="fa-solid fa-trash-can-slash"></i></a>
                    {% endif %}
                {% endif %}
                <div class="card-title">
                    Author:
                    {{ photo.owner.get_full_name }}
                </div>
                <div>Title: {{ photo.name }}</div>
                <div class="card-body">Description: {{ photo.description }}</div>
                {% include 'likes.html' %}
                <i class="fa-solid fa-message"></i> {{ photo.comment_count }}
                <div class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                        <form id="create-comment-form" data-photo-id="{{ photo.id }}"
                              name="comment">
                            <label for="create-comment-text-area">Leave comment</label>
                            <textarea name="comment-text" class="form-control" id="create-comment-text-area"
                                      type="comment"
                                      rows="3"></textarea>
                            <button type="submit" class="btn btn-warning">Submit</button>
                        </form>
                    {% endif %}
                    <div class="comments">
{#                        {% include 'comments.html' with comment_list=photo.comments.all %}#}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/ajax_likes.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax_comments.js' %}"></script>
{% endblock %}

web_site/templates/photo_upload.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% block content %}
    <form action="{% url 'web_site:photo_upload' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% bootstrap_form upload_form %}
        {% buttons %}
            <button type="submit" class="btn btn-warning">{% translate 'Submit' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

web_site/templates/register.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% block content %}
  <h1>{% translate "Create an account" %}</h1>
  <form action="." method="post">
    {% csrf_token %}
    {% bootstrap_form registration_form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">{% translate 'Create account' %}</button>
    {% endbuttons %}
  </form>
{% endblock %}